### ISSUE TITLE
Wrong mount path

### ISSUE THREAD

**Issue by Synchro** [bpiselli/ansible-scaleway-mount#1]
I specified my scaleway mount like this (in a `host_vars` file):

```
cloud_mounts:
    - source: '/dev/nbd1'
      destination: '/data'
      fstype: 'ext4'
```

But when it ran:

```
changed: []> (item={u'source': u'/dev/nbd1', u'destination': u'/mnt/data', u'fstype': u'ext4'}) => {"changed": true, "item": {"destination": "/mnt/data", "fstype": "ext4", "source": "/dev/nbd1"}}
```

It used `/mnt/data` instead of `/data`. Did I do something wrong?
